SiteFouYou/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('blogs.urls')),
    path('', include('blogs.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/urls.py
# /bin/bash/python3
# -*- coding:utf8 -*-
# @Time: 2022/1/3 12:20
from django.urls import path, re_path, register_converter
from . import views, converts

# register_converter(converts.FilterConverts, 'filter')

app_name = 'blogs'
urlpatterns = [
    path('home/', views.home, name='home'),
    path('up_or_down/', views.up_or_down, name='up_or_down'),  # up_or_down会被匹配成用户名，要放置到前面
    path('comment/', views.comment, name='comment'),
    # 后台管理
    path('backend/', views.backend, name='backend'),
    # 文章
    path('backend/new_blog/', views.new_blog, name='new_blog'),
    path('backend/edit_blog/<int:pk>/', views.edit_blog, name='edit_blog'),
    path('backend/delete_blog/<int:pk>/', views.delete_blog, name='delete_blog'),
    # 分类
    path('backend/new_category/', views.new_category, name='new_category'),
    path('backend/edit_category/<int:pk>/', views.edit_category, name='edit_category'),
    path('backend/delete_category/<int:pk>/', views.delete_category, name='delete_category'),
    # 标签
    path('backend/new_tag/', views.new_tag, name='new_tag'),
    path('backend/edit_tag/<int:pk>/', views.edit_tag, name='edit_tag'),
    path('backend/delete_tag/<int:pk>/', views.delete_tag, name='delete_tag'),

    # 页面展示
    path('<str:username>/', views.user_site, name='user_site'),
    path('<str:username>/p/<int:pk>/', views.blog_details, name='detail'),
    re_path(r'^(?P<username>\w+)/(?P<flag>tag|category|archive)/(?P<param>.*)/$', views.user_site, name='filter'),

]

users/urls.py
# /bin/bash/python3
# -*- coding:utf8 -*-
# @Time: 2022/1/3 18:18
from django.urls import path
from users import views

app_name = 'users'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('get_code/<int:refresh>', views.get_code, name='get_code'),
    path('set_pwd/', views.set_pwd, name='set_pwd'),
]

blogs/forms.py
# /bin/bash/python3
# -*- coding:utf8 -*-
# @Time: 2022/1/22 22:42
from django import forms
from blogs import models
from mdeditor.widgets import MDEditorWidget


class BlogForm(forms.ModelForm):
    class Meta:
        model = models.Blog
        fields = ['title', 'excerpt', 'content', 'cover']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'excerpt': forms.TextInput(attrs={'class': 'form-control'}),
            'content': MDEditorWidget(attrs={'class': 'pull-left'}),
            'cover': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'category': forms.RadioSelect(attrs={'class': 'form-control'}),
            'tags': forms.CheckboxSelectMultiple(attrs={'class': 'form-control'}),
        }


class CategoryForm(forms.ModelForm):
    """分类表单"""

    class Meta:
        model = models.Category
        fields = ['name']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'})
        }


class TagForm(forms.ModelForm):
    """标签表单"""

    class Meta:
        model = models.Tag
        fields = ['name']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'})
        }

users/forms.py
# /bin/bash/python3
# -*- coding:utf8 -*-
# @Time: 2022/1/3 15:48
from django import forms
from users.models import Author


class RegForm(forms.Form):
    """用户注册表单"""
    username = forms.CharField(
        label='用户名',
        min_length=3,
        max_length=8,
        error_messages={
            'required': '用户名不能为空',
            'min_length': '用户名不能少于3位',
            'max_length': '用户名不能大于8位'
        },
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': '用户名'
        }),
        help_text=['必填；', '用户名不得重名。']
    )
    password = forms.CharField(
        label='密码',
        min_length=3,
        max_length=20,
        error_messages={
            'required': '密码不能为空',
            'min_length': '密码不能少于3位',
            'max_length': '密码不能大于20位'
        },
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': '密码'}),
        help_text=['你的密码必须包含至少 3 个字符；', '你的密码必须包含不能大于 20 个字符。']
    )
    confirm_password = forms.CharField(
        label='确认密码',
        min_length=3,
        max_length=20,
        error_messages={
            'required': '请输入与上面相同的密码',
        },
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': '密码确认'}),
        help_text=['为了校验，请输入与上面相同的密码。']
    )
    link = forms.EmailField(
        label='邮箱',
        error_messages={
            'required': '邮箱不能为空',
            'invalid': '无效的邮箱格式'
        },
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': '邮箱'}),
        help_text=['邮箱不能为空。']
    )

    # avatar = forms.ImageField(
    #     label='头像'
    # )

    def clean_username(self):
        """校验用户名是否存在"""
        username = self.cleaned_data.get("username")
        is_exist = Author.objects.filter(username=username)
        if is_exist:
            self.add_error('username', '用户名已存在')
        return username

    def clean(self):
        """全局校验"""
        password = self.cleaned_data.get("password")
        confirm_pwd = self.cleaned_data.get("confirm_password")
        if password != confirm_pwd:
            self.add_error('confirm_password', '两次输入的密码不一致')
        return self.cleaned_data


class LoginForm(forms.Form):
    """用户登陆表单"""
    username = forms.CharField(
        label='用户名',
        min_length=3,
        max_length=8,
        error_messages={
            'required': '用户名不能为空',
            'min_length': '用户名不能少于3位',
            'max_length': '用户名不能大于8位'
        },
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': '用户名'
        }),
    )
    password = forms.CharField(
        label='密码',
        min_length=3,
        max_length=20,
        error_messages={
            'required': '密码不能为空',
        },
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': '密码'}),
    )

    def clean_username(self):
        """校验用户名是否存在"""
        username = self.cleaned_data.get("username")
        is_exist = Author.objects.filter(username=username)
        if not is_exist:
            self.add_error('username', '用户名不存在，请前往注册')
        return username

blogs/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Count, F
from django.db.models.functions import TruncMonth
from django.db import transaction
from django.contrib.auth.decorators import login_required
from django.urls import reverse

from blogs.models import Blog, Comment, Category, Tag, UpAndDown, Tag4Blog
from blogs.forms import BlogForm, CategoryForm, TagForm
from users.models import Author

from datetime import datetime
import markdown
from distutils.util import strtobool


# Create your views here.

def home(request):
    """
    主页面
    展示所有blog（不区分用户）
    """
    user = request.user
    blog_queryset = Blog.objects.all().order_by('-create_time')
    return render(request, 'blogs/home.html', context={'user': user, 'blog_queryset': blog_queryset})


def user_site(request, username, **kwargs):
    """展示当前站点（用户）下所有文章"""
    user_obj = Author.objects.filter(username=username).first()
    if not user_obj:
        return render(request, 'blogs/404.html')
    # 一对一站点
    cur_user_site = user_obj.usersite
    blog_list = Blog.objects.filter(author__username=username)
    if kwargs:
        flag = kwargs.get('flag')
        param = kwargs.get('param')
        if flag == 'tag':
            blog_list = blog_list.filter(tags__id=param)
        elif flag == 'category':
            blog_list = blog_list.filter(category__id=param)
        elif flag == 'archive':
            _date = datetime.strptime(param, '%Y-%m')
            blog_list = blog_list.filter(create_time__year=_date.year, create_time__month=_date.month)
        else:
            redirect('blogs:home')

    # 分类筛选
    category_list = Category.objects.filter(
        user_site=cur_user_site).annotate(count_num=Count('blog__pk')).values_list('name', 'count_num', 'pk')
    # 标签筛选 （标签名，基数值）
    tag_list = Tag.objects.filter(user_site=cur_user_site).annotate(
        count_num=Count('blog__pk')).values_list('name', 'count_num', 'pk')
    # 日期筛选（按月筛选）
    date_list = Blog.objects.filter(user_site=cur_user_site).annotate(month=TruncMonth('create_time')).values(
        'month').annotate(
        c=Count('pk')).values_list('month', 'c')
    return render(request, 'blogs/user_site.html', context=locals())


def blog_details(request, username, pk):
    """blog内容明细展示"""

    blog = Blog.objects.filter(pk=pk, author__username=username).first()
    if not blog:
        return render(request, 'blogs/404.html')
    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
    ])
    blog.content = md.convert(blog.content)

    # 评论展示
    comment_list = Comment.objects.filter(blog=blog)
    # for comment_obj in Comment.objects.filter(blog=blog):
    #     parent_id = comment_obj.parent_id
    #     if parent_id is not None:
    #         parent_obj = Comment.objects.get(pk=parent_id)
    #         parent_obj.child_cm = comment_obj
    #         comment_list.append(parent_obj)
    #     else:
    #         comment_list.append(comment_obj)
    context = {
        'username': username,
        'blog_id': pk,
        'blog': blog,
        'toc': md.toc,
        'comment_list': comment_list,
    }
    return render(request, 'blogs/blog_details.html', context=context)


def up_or_down(request):
    """
    blog内容中的：点赞点踩逻辑
        # 1. 判断用户是否登陆
        # 2. 判断用户是否给自己的文章点赞
        # 3. 判断是否已经点过赞
    """
    if request.is_ajax():
        back_dic = {'code': 1000, 'msg': ''}
        # 是否登录
        blog_id = request.POST['blog_id']
        blog = Blog.objects.get(pk=blog_id)
        if request.user.is_authenticated:
            is_up = bool(strtobool(request.POST['is_up']))
            # 是否本人点赞
            if request.user != blog.author:
                is_already_click = UpAndDown.objects.filter(user=request.user, blog=blog)
                if not is_already_click:
                    if is_up:
                        Blog.objects.filter(pk=blog_id).update(up_num=F('up_num') + 1)
                        back_dic['code'] = 1001
                        back_dic['msg'] = '点赞成功'
                    else:
                        Blog.objects.filter(pk=blog_id).update(down_num=F('down_num') + 1)
                        back_dic['code'] = 1002
                        back_dic['msg'] = '点踩成功'
                    UpAndDown.objects.create(user=request.user, blog=blog, is_up=is_up)
                # 已经点过赞/踩
                else:
                    back_dic['msg'] = '不可重复操作'
                    back_dic['code'] = 1003
            # 给自己的文章点赞
            else:
                back_dic['msg'] = '不能给自己的文章点赞/踩ooo'
                back_dic['code'] = 1004
        else:
            back_dic['msg'] = '用户未登录，<a href=/users/login/?next=/{}/p/{}>请登录</a>'.format(blog.author, blog_id)
            back_dic['code'] = 1005
        return JsonResponse(back_dic)
    else:
        return HttpResponse("wrong number: 500")


def comment(request):
    """blog明细中的评论逻辑"""
    if request.is_ajax():
        back_dic = {'code': 1000, 'msg': ''}
        if request.user.is_authenticated:
            blog_id = request.POST['blog_id']
            parent_id = request.POST['parentId']
            cm_content = request.POST['cm_content']
            with transaction.atomic():
                Blog.objects.filter(pk=blog_id).update(comment_num=F('comment_num') + 1)
                blog_obj = Blog.objects.get(pk=blog_id)
                cm_obj = Comment.objects.create(comment_user=request.user, blog_id=blog_id, content=cm_content,
                                                parent_id=parent_id)
            tmp_render = '<li class="list-group-item">\
                        <p class="list-group-item-heading" style="padding:8xp;padding-right:7px">\
                            <span style="margin-left:5px">{}</span>\
                            <span style="margin-left:5px">{}</span>\
                            <span class="pull-right reply"><a href="#id_comment">回复</a></span>\
                        </p>\
                        <h4 class="list-group-item-text">{}</h4>\
                    </li>'
            back_dic['code'] = 1000
            back_dic['msg'] = '<p style="color:#337ab7"><br>评论成功!!<br></p> %s' % tmp_render.format(cm_obj.comment_time,
                                                                                                   cm_obj.comment_user,
                                                                                                   cm_content)
            if parent_id:
                back_dic['msg'] = '<p style="color:#337ab7"><br>评论成功!!<br></p> %s' % tmp_render.format(
                    '@%s' % cm_obj.parent.comment_user.username, cm_obj.comment_time, cm_obj.comment_user, cm_content)
        else:
            back_dic['code'] = 1001
            back_dic['msg'] = '用户未登录'
        return JsonResponse(back_dic)


@login_required
def backend(request):
    """后台管理页面"""
    blog_list = Blog.objects.filter(author=request.user)
    tag_list = Tag.objects.filter(user_site=request.user.usersite)
    category_list = Category.objects.filter(user_site=request.user.usersite)
    context = {
        'user': request.user,
        'blog_list': blog_list,
        'tag_list': tag_list,
        'category_list': category_list,
    }
    return render(request, 'blogs/backend/backend.html', context=context)


@login_required
def new_blog(request):
    """添加新文章"""
    if request.method == 'GET':
        blog_form = BlogForm()
    else:
        blog_form = BlogForm(request.POST)
        if blog_form.is_valid():
            clean_data = blog_form.cleaned_data
            category_id = request.POST['category']
            tag_ids = request.POST.getlist('tag')
            _blog = Blog.objects.create(
                title=clean_data['title'],
                content=clean_data['content'],
                excerpt=clean_data['excerpt'],
                cover=clean_data['cover'],
                user_site=request.user.usersite,
                author=request.user,
                category_id=category_id
            )
            tag_blog_list = [Tag4Blog(blog=_blog, tag_id=_id) for _id in tag_ids]
            Tag4Blog.objects.bulk_create(tag_blog_list)
            return redirect(reverse('blogs:backend'))

    # 过滤当前用户站点下的标签、分类
    tag_list = Tag.objects.filter(user_site__user=request.user)
    category_list = Category.objects.filter(user_site__user=request.user)
    context = {
        'user': request.user,
        'form': blog_form,
        'tag_list': tag_list,
        'category_list': category_list,
    }
    return render(request, 'blogs/backend/new_blog.html', context)


@login_required
def edit_blog(request, pk):
    """编辑/更新新文章"""
    blog_obj = Blog.objects.get(pk=pk)

    # 如果获取不到blog对象/不是文章作者本人，则返回404
    if not blog_obj or blog_obj.author != request.user:
        return render(request, 'blogs/404.html')
    # 处理请求
    if request.method == 'GET':
        blog_form = BlogForm(instance=blog_obj)
    else:
        blog_form = BlogForm(instance=blog_obj, data=request.POST)
        if blog_form.is_valid():
            category_id = request.POST['category']
            tag_ids = request.POST.getlist('tag')
            blog_edited = blog_form.save(commit=False)
            # 更新分类信息
            blog_edited.category_id = category_id
            blog_edited.save()

            # 先删除blog_id所有的tag，再重新添加
            Tag4Blog.objects.filter(blog_id=pk).delete()
            tag_blog_list = [Tag4Blog(blog_id=pk, tag_id=_id) for _id in tag_ids]
            Tag4Blog.objects.bulk_create(tag_blog_list)

            return redirect(reverse('blogs:backend'))
    selected_category = Category.objects.get(pk=blog_obj.category_id)
    selected_tag4blogs = Tag4Blog.objects.filter(blog_id=pk)
    tag_list = Tag.objects.filter(user_site__user=request.user)
    category_list = Category.objects.filter(user_site__user=request.user)
    context = {

templates/blogs/base.html
<!DOCTYPE html>
{% load static %}
<html lang="zh-hans">
<head>
    <meta charset="UTF-8">
    <title>{% block page_title%} {% endblock %}</title>
    <link rel="shortcut icon" href="#" />
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
          integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" rel="stylesheet">
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/twitter-bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>


        #site-header {
            padding: 5px 1px;

        }
        .sidebar-block h3 {
            color: #fff;
            background-color: #337ab7;
            border-color: #337ab7;
            font-size: 18px;
            font-weight: normal;
            padding: 15px 20px;
            margin-top:0px;
            margin-bottom:0px
        }
        .mg {
            margin-top:10px;
            margin-bottom:10px;
        }
        .area_title {
            font-size: 14px;
            font-weight: bold;
            margin: 20px 0 10px;
        }
        {% block personal_style %}
        {% endblock %}

    </style>

</head>
<body>
<!--导航条-->
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div id="site-header" class="font-style">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">
                    {% block brand %} {% endblock %}
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li class=""><a href="{% url 'blogs:home' %}">博客 <span class="sr-only">(current)</span></a></li>
                    {%if user.is_authenticated %}
                    <li><a href="{% url 'blogs:user_site' user.username %}">文章</a></li>
                    {% endif %}
                    <!--                <li class="dropdown">-->
                    <!--                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"-->
                    <!--                       aria-expanded="false">Dropdown <span class="caret"></span></a>-->
                    <!--                    <ul class="dropdown-menu">-->
                    <!--                        <li><a href="#">Action</a></li>-->
                    <!--                        <li><a href="#">Another action</a></li>-->
                    <!--                        <li><a href="#">Something else here</a></li>-->
                    <!--                        <li role="separator" class="divider"></li>-->
                    <!--                        <li><a href="#">Separated link</a></li>-->
                    <!--                        <li role="separator" class="divider"></li>-->
                    <!--                        <li><a href="#">One more separated link</a></li>-->
                    <!--                    </ul>-->
                    <!--                </li>-->
                </ul>
                <form class="navbar-form navbar-left">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Search">
                    </div>
                    <button type="submit" class="btn btn-default">Submit</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                           aria-expanded="false">
                            <img src="{{ user.avatar.url }}" class="img-circle center" alt="..." width="24px"
                                 height="24px">
                            <span style="font-size: 16px;font-weight:bold">{{ user.username }}</span>
                            <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a data-toggle="modal" data-target="#myModal">修改密码</a></li>
                            <li><a href="#">修改头像</a></li>
                            <li><a href="{% url 'blogs:backend' %}">后台管理</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="{% url 'users:logout' %}">退出登录</a></li>
                        </ul>
                    </li>

                    <!--            模态框    -->
                    <div id="myModal" class="modal fade" tabindex="-1" role="dialog">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <!--                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>-->
                                    <h2 class="modal-title text-center">修改密码</h2>
                                </div>
                                <div class="modal-body">
                                    <div class="form-group">
                                        <label>用户名</label>
                                        <input type="text" name="id_username" value="{{ user.username }}"
                                               class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <label>原密码</label>
                                        <input type="password" id="id_old_password" name="old_password"
                                               class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <label>新密码</label>
                                        <input type="password" id="id_new_password" name="new_password"
                                               class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <label>确认密码</label>
                                        <input type="password" id="id_confirm_password" name="confirm_password"
                                               class="form-control">
                                    </div>
                                </div>

                                <div class="modal-footer">
                                    <span style="color:red" class="pull-left" id="set_pwd_error"> </span>
                                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                                    <button type="button" class="btn btn-primary" id="save_pwd">确认修改</button>
                                </div>
                            </div><!-- /.modal-content -->
                        </div><!-- /.modal-dialog -->
                    </div><!-- /.modal -->

                    {% else %}
                    <li><a href="{% url 'users:register' %}">注册</a></li>
                    <li><a href="{% url 'users:login' %}">登录</a></li>
                    {% endif %}

                </ul>
            </div><!-- /.navbar-collapse -->
        </div>
    </div><!-- /.container-fluid -->
</nav>

{% block content %}
{% endblock %}

<script>
    $(function (){
        $('#save_pwd').click(function () {
            $.ajax({
                    url: '{% url 'users:set_pwd' %}',
                    type: 'post',
                    data: {
                        'old_password': $('#id_old_password').val(),
                        'new_password': $('#id_new_password').val(),
                        'confirm_password': $('#id_confirm_password').val(),
                        'csrfmiddlewaretoken': '{{ csrf_token }}'
                    },
                    success: function(args) {
                        if (args.code == 1000) {
                            alert(args.msg)
                            window.location.reload()
                        } else  {
                            $('#set_pwd_error').text(args.msg)
                        }
                    }
                });
        })
    })








</script>
{% block script %}
{% endblock %}
</body>
</html>

templates/blogs/home.html
{% extends 'blogs/base.html'%}
{% block page_title%} SiteForYou {% endblock %}
{% block brand %}
YOU SITE
{% endblock %}
{% block content %}
<!--# 博客列表-->
<div class="container">
    <ul class="media-list">
        {% for blog in blog_queryset %}
        <li class="media">
            <h2 class="media-heading" style="margin-bottom:9px"><a href="{% url 'blogs:detail' blog.author blog.pk %}">{{ blog.title }}</a></h2>
            <div class="media-left">
                <a href="#">
                    <img class="media-object" src="{{ blog.author.avatar.url }}" alt="..." width="80">
                </a>
            </div>
            <div class="media-body">
                {{ blog.excerpt }}
            </div>
        </li>
        <br>
        <span><a
                href="{% url 'blogs:user_site' blog.author.username %}">{{ blog.author.username }}&nbsp;&nbsp;</a></span>
        <span>{{ blog.create_time | date:'Y-m-d H:i' }}&nbsp;&nbsp;</span>
        <span><span class="glyphicon glyphicon-thumbs-up" style="margin-right:4px"></span>{{ blog.up_num }} &nbsp;&nbsp;</span>
        <span><span class="glyphicon glyphicon-comment" style="margin-right:4px"></span>{{ blog.comment_num }} &nbsp;&nbsp;</span>
        <hr>
        {% endfor %}

    </ul>
</div>
{% endblock %}

templates/blogs/left_menu.html
<div class="sidebar-block">
    <h3>文章分类</h3>
    <ul class="list-group">
        {% for category in category_list %}
        <li class="list-group-item"><a href="{% url 'blogs:filter' user_obj.username 'category' category.2  %}">{{ category.0 }} ({{ category.1 }})</a></li>
        {% endfor %}
    </ul>

</div>

<div class="sidebar-block">
    <h3>我的标签</h3>
    <ul class="list-group">
        {% for tag in tag_list %}
        <li class="list-group-item"><a href="{% url 'blogs:filter' user_obj.username 'tag'  tag.2  %}">{{ tag.0 }} ({{ tag.1 }})</a></li>
        {% endfor %}
     </ul>

</div>

<div class="sidebar-block">
    <h3>随笔归档</h3>
    <ul class="list-group">
        {% for date in date_list %}
        <li class="list-group-item" style="border-radius: 5px;"><a
                href="{% url 'blogs:filter' user_obj.username 'archive'  date.0|date:'Y-m'  %}">{{ date.0 |date:"Y年m月" }} ({{ date.1 }})</a></li>
        {% endfor %}
    </ul>
</div>

templates/blogs/user_site.html
{% extends 'blogs/base.html'%}

# 个人站点样式
{% block personal_style %}
{{  cur_user_site.site_theme }}
{% endblock %}

{% block page_title%} 主页 {% endblock %}
{% block brand %}
{{ username }}
{% endblock %}
{% block content %}
<!--# 博客列表-->
<div class="container-fluid" style="margin-top:10px;">
    <div class="row">
        <!--       标签、分类 -->
        <div class="col-md-2">
            {% load blogs_tag %}
            {% left_menu username %}
        </div>
        <!--        user博客列表-->
        <div class="col-md-10">
            {% if blog_list %}
            <ul class="media-list">
                {% for blog in blog_list %}
                <li class="media">
                    <h2 class="media-heading" style="margin-bottom:9px"><a href="{% url 'blogs:detail' blog.author blog.pk %}">{{ blog.title }}</a></h2>
                    <div class="media-left">
                        <a href="#">
                            <img class="media-object" src="{{ blog.author.avatar.url }}" alt="..." width="80">
                        </a>
                    </div>
                    <div class="media-body">
                        {{ blog.excerpt }}
                    </div>
                </li>
                <br>
<!--                posted @ 2022-01-14 19:59 捉虫大师 评论(0) 推荐(0) 编辑-->
                <div class="pull-right">
                <span>posted&nbsp;@&nbsp;{{ blog.create_time | date:'Y-m-d H:i' }}&nbsp;&nbsp;</span>
                <span>{{ blog.author.username }}&nbsp;&nbsp;</span>
                <span><span class="glyphicon glyphicon-thumbs-up" style="margin-right:4px"></span>{{ blog.up_num }} &nbsp;&nbsp;</span>
                <span><span class="glyphicon glyphicon-comment" style="margin-right:4px"></span>{{ blog.comment_num }} &nbsp;&nbsp;</span>
                <span><a href="#">编辑&nbsp;&nbsp;</a></span>
                </div>
                <br>
                <hr>
                {% endfor %}
                {% else %}
                <div class="jumbotron center-block" style="padding-bottom:55%">
                    <p class="pull-center">这个人很懒，什么都没有留下</p>
                </div>
                {% endif %}
            </ul>
        </div>
    </div>

</div>
{% endblock %}