SiteFouYou/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('blogs.urls')),
    path('', include('blogs.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/urls.py
# /bin/bash/python3
# -*- coding:utf8 -*-
# @Time: 2022/1/3 12:20
from django.urls import path, re_path, register_converter
from . import views, converts

# register_converter(converts.FilterConverts, 'filter')

app_name = 'blogs'
urlpatterns = [
    path('home/', views.home, name='home'),
    path('up_or_down/', views.up_or_down, name='up_or_down'),  # up_or_down会被匹配成用户名，要放置到前面
    path('comment/', views.comment, name='comment'),
    # 后台管理
    path('backend/', views.backend, name='backend'),
    # 文章
    path('backend/new_blog/', views.new_blog, name='new_blog'),
    path('backend/edit_blog/<int:pk>/', views.edit_blog, name='edit_blog'),
    path('backend/delete_blog/<int:pk>/', views.delete_blog, name='delete_blog'),
    # 分类
    path('backend/new_category/', views.new_category, name='new_category'),
    path('backend/edit_category/<int:pk>/', views.edit_category, name='edit_category'),
    path('backend/delete_category/<int:pk>/', views.delete_category, name='delete_category'),
    # 标签
    path('backend/new_tag/', views.new_tag, name='new_tag'),
    path('backend/edit_tag/<int:pk>/', views.edit_tag, name='edit_tag'),
    path('backend/delete_tag/<int:pk>/', views.delete_tag, name='delete_tag'),

    # 页面展示
    path('<str:username>/', views.user_site, name='user_site'),
    path('<str:username>/p/<int:pk>/', views.blog_details, name='detail'),
    re_path(r'^(?P<username>\w+)/(?P<flag>tag|category|archive)/(?P<param>.*)/$', views.user_site, name='filter'),

]

blogs/models.py
from django.db import models
from mdeditor.fields import MDTextField


# Create your models here.
class UserSite(models.Model):
    """个人站点表"""
    site_title = models.CharField(verbose_name='站点标题', max_length=32)
    site_name = models.CharField(verbose_name='站点名称', max_length=32)
    site_theme = models.TextField(verbose_name='站点样式表', blank=True, null=True, max_length=64)  # 存储css样式

    user = models.OneToOneField(to='users.Author', null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.site_title


class Category(models.Model):
    """分类表"""
    name = models.CharField(max_length=20, verbose_name="分类名")
    user_site = models.ForeignKey(to='UserSite', null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Tag(models.Model):
    """标签表"""
    name = models.CharField(max_length=20, verbose_name="标签名")
    user_site = models.ForeignKey(to='UserSite', null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Blog(models.Model):
    """
    Blog内容表
    """
    title = models.CharField(max_length=64, verbose_name='标题')
    excerpt = models.CharField(max_length=255, blank=True, null=True, verbose_name='摘要')
    content = MDTextField(verbose_name='内容')

    create_time = models.DateTimeField(auto_now_add=True)
    modified_time = models.DateTimeField(auto_now=True)
    cover = models.ImageField(blank=True, null=True, verbose_name='封面')

    user_site = models.ForeignKey(to='UserSite', on_delete=models.CASCADE)
    author = models.ForeignKey('users.Author', null=True, on_delete=models.CASCADE, verbose_name='作者')
    category = models.ForeignKey('Category', null=True, on_delete=models.SET_NULL, verbose_name='分类')
    tags = models.ManyToManyField('Tag', through='Tag4Blog', through_fields=('blog', 'tag'), verbose_name='标签')

    up_num = models.BigIntegerField(default=0, verbose_name='点赞数')
    down_num = models.BigIntegerField(default=0, verbose_name='点踩数')
    comment_num = models.BigIntegerField(default=0, verbose_name='评论数')

    def __str__(self):
        return self.title


class Tag4Blog(models.Model):
    """
    tag 中间表
    所有数据外键都是级联删除，没有单独存在的必要
    """
    tag = models.ForeignKey(to='Tag', on_delete=models.CASCADE)
    blog = models.ForeignKey(to='Blog', on_delete=models.CASCADE)


class Comment(models.Model):
    """
    评论表：自关联
    """
    comment_user = models.ForeignKey(to='users.Author', on_delete=models.CASCADE, null=True, verbose_name="评论人")
    blog = models.ForeignKey(to='Blog', on_delete=models.CASCADE, verbose_name="评论文章")
    content = models.CharField(max_length=255, verbose_name='评论内容')
    comment_time = models.DateTimeField(auto_now_add=True, verbose_name='评论时间')
    parent = models.ForeignKey(to='self', on_delete=models.CASCADE, blank=True, null=True, verbose_name='根评论')

    def __str__(self):
        return self.content


class UpAndDown(models.Model):
    """点赞点踩表"""
    user = models.ForeignKey(to='users.Author', on_delete=models.CASCADE)
    blog = models.ForeignKey(to='Blog', on_delete=models.CASCADE)
    is_up = models.BooleanField()

blogs/forms.py
# /bin/bash/python3
# -*- coding:utf8 -*-
# @Time: 2022/1/22 22:42
from django import forms
from blogs import models
from mdeditor.widgets import MDEditorWidget


class BlogForm(forms.ModelForm):
    class Meta:
        model = models.Blog
        fields = ['title', 'excerpt', 'content', 'cover']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'excerpt': forms.TextInput(attrs={'class': 'form-control'}),
            'content': MDEditorWidget(attrs={'class': 'pull-left'}),
            'cover': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'category': forms.RadioSelect(attrs={'class': 'form-control'}),
            'tags': forms.CheckboxSelectMultiple(attrs={'class': 'form-control'}),
        }


class CategoryForm(forms.ModelForm):
    """分类表单"""

    class Meta:
        model = models.Category
        fields = ['name']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'})
        }


class TagForm(forms.ModelForm):
    """标签表单"""

    class Meta:
        model = models.Tag
        fields = ['name']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'})
        }

blogs/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Count, F
from django.db.models.functions import TruncMonth
from django.db import transaction
from django.contrib.auth.decorators import login_required
from django.urls import reverse

from blogs.models import Blog, Comment, Category, Tag, UpAndDown, Tag4Blog
from blogs.forms import BlogForm, CategoryForm, TagForm
from users.models import Author

from datetime import datetime
import markdown
from distutils.util import strtobool


# Create your views here.

def home(request):
    """
    主页面
    展示所有blog（不区分用户）
    """
    user = request.user
    blog_queryset = Blog.objects.all().order_by('-create_time')
    return render(request, 'blogs/home.html', context={'user': user, 'blog_queryset': blog_queryset})


def user_site(request, username, **kwargs):
    """展示当前站点（用户）下所有文章"""
    user_obj = Author.objects.filter(username=username).first()
    if not user_obj:
        return render(request, 'blogs/404.html')
    # 一对一站点
    cur_user_site = user_obj.usersite
    blog_list = Blog.objects.filter(author__username=username)
    if kwargs:
        flag = kwargs.get('flag')
        param = kwargs.get('param')
        if flag == 'tag':
            blog_list = blog_list.filter(tags__id=param)
        elif flag == 'category':
            blog_list = blog_list.filter(category__id=param)
        elif flag == 'archive':
            _date = datetime.strptime(param, '%Y-%m')
            blog_list = blog_list.filter(create_time__year=_date.year, create_time__month=_date.month)
        else:
            redirect('blogs:home')

    # 分类筛选
    category_list = Category.objects.filter(
        user_site=cur_user_site).annotate(count_num=Count('blog__pk')).values_list('name', 'count_num', 'pk')
    # 标签筛选 （标签名，基数值）
    tag_list = Tag.objects.filter(user_site=cur_user_site).annotate(
        count_num=Count('blog__pk')).values_list('name', 'count_num', 'pk')
    # 日期筛选（按月筛选）
    date_list = Blog.objects.filter(user_site=cur_user_site).annotate(month=TruncMonth('create_time')).values(
        'month').annotate(
        c=Count('pk')).values_list('month', 'c')
    return render(request, 'blogs/user_site.html', context=locals())


def blog_details(request, username, pk):
    """blog内容明细展示"""

    blog = Blog.objects.filter(pk=pk, author__username=username).first()
    if not blog:
        return render(request, 'blogs/404.html')
    md = markdown.Markdown(extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
    ])
    blog.content = md.convert(blog.content)

    # 评论展示
    comment_list = Comment.objects.filter(blog=blog)
    # for comment_obj in Comment.objects.filter(blog=blog):
    #     parent_id = comment_obj.parent_id
    #     if parent_id is not None:
    #         parent_obj = Comment.objects.get(pk=parent_id)
    #         parent_obj.child_cm = comment_obj
    #         comment_list.append(parent_obj)
    #     else:
    #         comment_list.append(comment_obj)
    context = {
        'username': username,
        'blog_id': pk,
        'blog': blog,
        'toc': md.toc,
        'comment_list': comment_list,
    }
    return render(request, 'blogs/blog_details.html', context=context)


def up_or_down(request):
    """
    blog内容中的：点赞点踩逻辑
        # 1. 判断用户是否登陆
        # 2. 判断用户是否给自己的文章点赞
        # 3. 判断是否已经点过赞
    """
    if request.is_ajax():
        back_dic = {'code': 1000, 'msg': ''}
        # 是否登录
        blog_id = request.POST['blog_id']
        blog = Blog.objects.get(pk=blog_id)
        if request.user.is_authenticated:
            is_up = bool(strtobool(request.POST['is_up']))
            # 是否本人点赞
            if request.user != blog.author:
                is_already_click = UpAndDown.objects.filter(user=request.user, blog=blog)
                if not is_already_click:
                    if is_up:
                        Blog.objects.filter(pk=blog_id).update(up_num=F('up_num') + 1)
                        back_dic['code'] = 1001
                        back_dic['msg'] = '点赞成功'
                    else:
                        Blog.objects.filter(pk=blog_id).update(down_num=F('down_num') + 1)
                        back_dic['code'] = 1002
                        back_dic['msg'] = '点踩成功'
                    UpAndDown.objects.create(user=request.user, blog=blog, is_up=is_up)
                # 已经点过赞/踩
                else:
                    back_dic['msg'] = '不可重复操作'
                    back_dic['code'] = 1003
            # 给自己的文章点赞
            else:
                back_dic['msg'] = '不能给自己的文章点赞/踩ooo'
                back_dic['code'] = 1004
        else:
            back_dic['msg'] = '用户未登录，<a href=/users/login/?next=/{}/p/{}>请登录</a>'.format(blog.author, blog_id)
            back_dic['code'] = 1005
        return JsonResponse(back_dic)
    else:
        return HttpResponse("wrong number: 500")


def comment(request):
    """blog明细中的评论逻辑"""
    if request.is_ajax():
        back_dic = {'code': 1000, 'msg': ''}
        if request.user.is_authenticated:
            blog_id = request.POST['blog_id']
            parent_id = request.POST['parentId']
            cm_content = request.POST['cm_content']
            with transaction.atomic():
                Blog.objects.filter(pk=blog_id).update(comment_num=F('comment_num') + 1)
                blog_obj = Blog.objects.get(pk=blog_id)
                cm_obj = Comment.objects.create(comment_user=request.user, blog_id=blog_id, content=cm_content,
                                                parent_id=parent_id)
            tmp_render = '<li class="list-group-item">\
                        <p class="list-group-item-heading" style="padding:8xp;padding-right:7px">\
                            <span style="margin-left:5px">{}</span>\
                            <span style="margin-left:5px">{}</span>\
                            <span class="pull-right reply"><a href="#id_comment">回复</a></span>\
                        </p>\
                        <h4 class="list-group-item-text">{}</h4>\
                    </li>'
            back_dic['code'] = 1000
            back_dic['msg'] = '<p style="color:#337ab7"><br>评论成功!!<br></p> %s' % tmp_render.format(cm_obj.comment_time,
                                                                                                   cm_obj.comment_user,
                                                                                                   cm_content)
            if parent_id:
                back_dic['msg'] = '<p style="color:#337ab7"><br>评论成功!!<br></p> %s' % tmp_render.format(
                    '@%s' % cm_obj.parent.comment_user.username, cm_obj.comment_time, cm_obj.comment_user, cm_content)
        else:
            back_dic['code'] = 1001
            back_dic['msg'] = '用户未登录'
        return JsonResponse(back_dic)


@login_required
def backend(request):
    """后台管理页面"""
    blog_list = Blog.objects.filter(author=request.user)
    tag_list = Tag.objects.filter(user_site=request.user.usersite)
    category_list = Category.objects.filter(user_site=request.user.usersite)
    context = {
        'user': request.user,
        'blog_list': blog_list,
        'tag_list': tag_list,
        'category_list': category_list,
    }
    return render(request, 'blogs/backend/backend.html', context=context)


@login_required
def new_blog(request):
    """添加新文章"""
    if request.method == 'GET':
        blog_form = BlogForm()
    else:
        blog_form = BlogForm(request.POST)
        if blog_form.is_valid():
            clean_data = blog_form.cleaned_data
            category_id = request.POST['category']
            tag_ids = request.POST.getlist('tag')
            _blog = Blog.objects.create(
                title=clean_data['title'],
                content=clean_data['content'],
                excerpt=clean_data['excerpt'],
                cover=clean_data['cover'],
                user_site=request.user.usersite,
                author=request.user,
                category_id=category_id
            )
            tag_blog_list = [Tag4Blog(blog=_blog, tag_id=_id) for _id in tag_ids]
            Tag4Blog.objects.bulk_create(tag_blog_list)
            return redirect(reverse('blogs:backend'))

    # 过滤当前用户站点下的标签、分类
    tag_list = Tag.objects.filter(user_site__user=request.user)
    category_list = Category.objects.filter(user_site__user=request.user)
    context = {
        'user': request.user,
        'form': blog_form,
        'tag_list': tag_list,
        'category_list': category_list,
    }
    return render(request, 'blogs/backend/new_blog.html', context)


@login_required
def edit_blog(request, pk):
    """编辑/更新新文章"""
    blog_obj = Blog.objects.get(pk=pk)

    # 如果获取不到blog对象/不是文章作者本人，则返回404
    if not blog_obj or blog_obj.author != request.user:
        return render(request, 'blogs/404.html')
    # 处理请求
    if request.method == 'GET':
        blog_form = BlogForm(instance=blog_obj)
    else:
        blog_form = BlogForm(instance=blog_obj, data=request.POST)
        if blog_form.is_valid():
            category_id = request.POST['category']
            tag_ids = request.POST.getlist('tag')
            blog_edited = blog_form.save(commit=False)
            # 更新分类信息
            blog_edited.category_id = category_id
            blog_edited.save()

            # 先删除blog_id所有的tag，再重新添加
            Tag4Blog.objects.filter(blog_id=pk).delete()
            tag_blog_list = [Tag4Blog(blog_id=pk, tag_id=_id) for _id in tag_ids]
            Tag4Blog.objects.bulk_create(tag_blog_list)

            return redirect(reverse('blogs:backend'))
    selected_category = Category.objects.get(pk=blog_obj.category_id)
    selected_tag4blogs = Tag4Blog.objects.filter(blog_id=pk)
    tag_list = Tag.objects.filter(user_site__user=request.user)
    category_list = Category.objects.filter(user_site__user=request.user)
    context = {

templates/blogs/backend/backend.html
{% extends 'blogs/backend/base.html' %}
{% block backend_content %}
<div>
    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="active"><a href="#article" aria-controls="article" role="tab"
                                                  data-toggle="tab">文章</a></li>
        <li role="presentation"><a href="#tag" aria-controls="profile" role="tab"
                                   data-toggle="tab">标签</a>
        </li>
        <li role="presentation"><a href="#category" aria-controls="messages" role="tab"
                                   data-toggle="tab">分类</a>
        </li>
        <li role="presentation"><a href="#settings" aria-controls="settings" role="tab"
                                   data-toggle="tab">设置</a>
        </li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
        <div role="tabpanel" class="tab-pane active" id="article">
            <!--标题发布状态 			操作	操作-->
            <table class="table table-hover table-striped">
                <thead>
                <tr>
                    <th colspan="2">标题</th>
                    <th>点赞</th>
                    <th>点踩</th>
                    <th>评论</th>
                    <th>操作</th>
                    <th>操作</th>
                </tr>
                </thead>
                {% for blog in blog_list %}
                <tr>
                    <td colspan="2"><a href="{% url 'blogs:detail' blog.author.username blog.pk %}">{{blog.title}}</a>
                    </td>
                    <td>{{blog.up_num}}</td>
                    <td>{{blog.down_num}}</td>
                    <td>{{blog.comment_num}}</td>
                    <td><a href="{% url 'blogs:edit_blog' blog.pk %}">编辑</a></td>
                    <td><a href="{% url 'blogs:delete_blog' blog.pk %}">删除</a></td>

                </tr>
                {% endfor %}
                <tr>
                    <th class="text-center" colspan="7"><a href="{% url 'blogs:new_blog' %}" class="addlink">增加文章</a>
                    </th>
                </tr>

            </table>
        </div>
        <div role="tabpanel" class="tab-pane" id="tag">
            <table class="table table-hover table-striped">
                <thead>
                <tr>
                    <th colspan="3">标签名</th>
                    <th>操作</th>
                    <th>操作</th>
                </tr>
                </thead>
                {% for tag in tag_list %}
                <tr>
                    <td colspan="3">{{ tag.name}}</td>
                    <td><a href="{% url 'blogs:edit_tag' tag.pk %}">编辑</a></td>
                    <td><a href="{% url 'blogs:delete_tag' tag.pk %}">删除</a></td>

                </tr>
                {% endfor %}
                <tr>
                    <th class="text-center" colspan="5"><a href="{% url 'blogs:new_tag' %}" class="addlink">增加标签</a>
                    </th>
                </tr>

            </table>
        </div>
        <div role="tabpanel" class="tab-pane" id="category">
            <table class="table table-hover table-striped">
                <thead>
                <tr>
                    <th colspan="3">分类名</th>
                    <th>操作</th>
                    <th>操作</th>
                </tr>
                </thead>
                {% for category in category_list %}
                <tr>
                    <td colspan="3">{{ category.name}}</td>
                    <td><a href="{% url 'blogs:edit_category' category.pk %}">编辑</a></td>
                    <td><a href="{% url 'blogs:delete_category' category.pk %}">删除</a></td>

                </tr>
                {% endfor %}
                <tr>
                    <th class="text-center" colspan="5"><a href="{% url 'blogs:new_category' %}"
                                                           class="addlink">增加分类</a></th>
                </tr>

            </table>
        </div>
        <div role="tabpanel" class="tab-pane" id="settings">
            {% block settings %}
            {% endblock %}
        </div>
    </div>
</div>

{% endblock %}

templates/blogs/backend/base.html
{% extends 'blogs/base.html'%}
{% load static %}
# 个人站点样式
{% block personal_style %}
.addlink {
    padding-left: 16px;
    background: url("{% static 'blogs/img/icon-addlink.svg' %}") 0 1px no-repeat;
}

{% endblock %}

{% block page_title%} 后台管理 {% endblock %}
{% block brand %}
{{ user.username }}
{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-2">
            <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                <div class="panel panel-default">
                    <div class="panel-heading" role="tab" id="headingOne">
                        <h4 class="panel-title">
                            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne"
                               aria-expanded="false" aria-controls="collapseOne">
                                更多操作
                            </a>
                        </h4>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel"
                         aria-labelledby="headingOne">
                        <div class="panel-body" style="padding:0px">
                            <ul id="more_article" class="list-group" style="margin-bottom:0px;">
                                <li class="list-group-item"><a href="{% url 'blogs:new_blog' %}">添加文章</a></li>
                                <li class="list-group-item"><a href="{% url 'blogs:new_category' %}">添加分类</a></li>
                                <li class="list-group-item"><a href="{% url 'blogs:new_tag' %}">添加标签</a></li>
                                <li class="list-group-item"><a href="{% url 'blogs:backend' %}">返回后台列表</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-10">
            {% block backend_content %}
            {% endblock%}
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script>

</script>
{% endblock %}

templates/blogs/backend/edit_blog.html
{% extends 'blogs/backend/base.html' %}
{% block backend_content %}
<div class="page-header">
    <h1>编辑文章</h1>
</div>
<form class="form" action="{% url 'blogs:edit_blog' blog_id %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">
        {{ field.label_tag }}
        {{ form.media }}
        {{ field }}
    </div>
    {% endfor %}

    <div class="form-group">
        <label>分类</label>
        <ul>
            {% for category in category_list %}
            <li><input type="radio" class="from-control" name="category" value="{{ category.pk }}"
                       {% if category.id == selected_category.id %} checked="checked" {% endif %}>{{ category.name }}
            </li>
            {% endfor %}
        </ul>
    </div>
    <div class="form-group">
        <label>标签</label>
        <ul>
            {% for tag in tag_list %}
            <li><input type="checkbox" class="from-control" name="tag" value="{{ tag.pk }}"
                       {% for selected_tag4blog in selected_tag4blogs %}
                       {% if tag.id == selected_tag4blog.tag_id %} checked="checked" 123213{% endif %}
                       {% endfor %}
            >{{ tag.name }}
            </li>
            {% endfor %}
        </ul>
    </div>

    <button type="submit" class="btn btn-primary">保存</button>
</form>
{% endblock %}

templates/blogs/backend/edit_category.html
{% extends 'blogs/backend/base.html' %}
{% block backend_content %}

<div class="page-header">
    <h1>编辑分类</h1>
</div>
<form class="form" action="{% url 'blogs:edit_category' category_id %}" method="post"
      enctype="application/x-www-form-urlencoded">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">
        {{ field.label_tag }}
        {{ field.errors.0 }}
        {{ field }}
    </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">保存</button>
</form>
{% endblock %}

templates/blogs/backend/edit_tag.html
{% extends 'blogs/backend/base.html' %}
{% block backend_content %}

<div class="page-header">
    <h1>编辑标签</h1>
</div>
<form class="form" action="{% url 'blogs:edit_tag' tag_id %}" method="post"
      enctype="application/x-www-form-urlencoded">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">
        {{ field.label_tag }}
        {{ field.errors.0 }}
        {{ field }}
    </div>
    {% endfor %}
    <button type="submit" class="btn btn-primary">保存</button>
</form>
{% endblock %}

templates/blogs/backend/new_blog.html
{% extends 'blogs/backend/base.html' %}
{% block backend_content %}
<div class="page-header"><h1>添加文章</h1></div>
<form class="form" action="{% url 'blogs:new_blog' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in form %}
    <div class="form-group">

        {{ field.label_tag }}
        {{ form.media }}
        {{ field }}
    </div>
    {% endfor %}

    <div class="form-group">
        <label>分类</label>
        <ul>
            {% for category in category_list %}
            <li><input type="radio" class="from-control" name="category" value="{{ category.pk }}">{{ category.name }}
            </li>
            {% endfor %}
        </ul>
    </div>
    <div class="form-group">
        <label>标签</label>
        <ul>
            {% for tag in tag_list %}
            <li><input type="checkbox" class="from-control" name="tag" value="{{ tag.pk }}">{{ tag.name }}</li>
            {% endfor %}
        </ul>
    </div>

    <button type="submit" class="btn btn-primary">保存</button>
</form>
{% endblock %}

templates/blogs/backend/new_category.html
{% extends 'blogs/backend/base.html' %}

{% block backend_content %}
<div class="page-header">
    <h1>添加分类：</h1>
</div>
<div role="tabpanel" class="tab-pane active" id="category">
    <form class="form" action="{% url 'blogs:new_category' %}" method="post"
          enctype="application/x-www-form-urlencoded">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
            {{ field.label_tag }}
            {{ field.errors.0 }}
            {{ field }}
        </div>
        {% endfor %}

        <button type="submit" class="btn btn-primary">保存</button>
    </form>
</div>
{% endblock %}

templates/blogs/backend/new_tag.html
{% extends 'blogs/backend/base.html' %}

{% block backend_content %}
<div class="page-header">
    <h1>添加标签：</h1>
</div>
<div role="tabpanel" class="tab-pane active" id="category">
    <form class="form" action="{% url 'blogs:new_tag' %}" method="post"
          enctype="application/x-www-form-urlencoded">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
            {{ field.label_tag }}
            {{ field.errors.0 }}
            {{ field }}
        </div>
        {% endfor %}

        <button type="submit" class="btn btn-primary">保存</button>
    </form>
</div>
{% endblock %}