SiteFouYou/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('blogs.urls')),
    path('', include('blogs.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/urls.py
# /bin/bash/python3
# -*- coding:utf8 -*-
# @Time: 2022/1/3 12:20
from django.urls import path, re_path, register_converter
from . import views, converts

# register_converter(converts.FilterConverts, 'filter')

app_name = 'blogs'
urlpatterns = [
    path('home/', views.home, name='home'),
    path('up_or_down/', views.up_or_down, name='up_or_down'),  # up_or_down会被匹配成用户名，要放置到前面
    path('comment/', views.comment, name='comment'),
    # 后台管理
    path('backend/', views.backend, name='backend'),
    # 文章
    path('backend/new_blog/', views.new_blog, name='new_blog'),
    path('backend/edit_blog/<int:pk>/', views.edit_blog, name='edit_blog'),
    path('backend/delete_blog/<int:pk>/', views.delete_blog, name='delete_blog'),
    # 分类
    path('backend/new_category/', views.new_category, name='new_category'),
    path('backend/edit_category/<int:pk>/', views.edit_category, name='edit_category'),
    path('backend/delete_category/<int:pk>/', views.delete_category, name='delete_category'),
    # 标签
    path('backend/new_tag/', views.new_tag, name='new_tag'),
    path('backend/edit_tag/<int:pk>/', views.edit_tag, name='edit_tag'),
    path('backend/delete_tag/<int:pk>/', views.delete_tag, name='delete_tag'),

    # 页面展示
    path('<str:username>/', views.user_site, name='user_site'),
    path('<str:username>/p/<int:pk>/', views.blog_details, name='detail'),
    re_path(r'^(?P<username>\w+)/(?P<flag>tag|category|archive)/(?P<param>.*)/$', views.user_site, name='filter'),

]

users/urls.py
# /bin/bash/python3
# -*- coding:utf8 -*-
# @Time: 2022/1/3 18:18
from django.urls import path
from users import views

app_name = 'users'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.log_in, name='login'),
    path('logout/', views.log_out, name='logout'),
    path('get_code/<int:refresh>', views.get_code, name='get_code'),
    path('set_pwd/', views.set_pwd, name='set_pwd'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.
def user_dir_path(instance, filename):
    return 'user_{0}/avatar/{1}'.format(instance.username, filename)


class Author(AbstractUser):
    """作者：用户名表"""
    link = models.CharField(verbose_name='联系方式', max_length=32, null=True)
    create_time = models.DateField(auto_now_add=True)
    avatar = models.FileField(upload_to=user_dir_path, default='uploads/avatar/default.jpg')

    def __str__(self):
        return self.username

users/forms.py
# /bin/bash/python3
# -*- coding:utf8 -*-
# @Time: 2022/1/3 15:48
from django import forms
from users.models import Author


class RegForm(forms.Form):
    """用户注册表单"""
    username = forms.CharField(
        label='用户名',
        min_length=3,
        max_length=8,
        error_messages={
            'required': '用户名不能为空',
            'min_length': '用户名不能少于3位',
            'max_length': '用户名不能大于8位'
        },
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': '用户名'
        }),
        help_text=['必填；', '用户名不得重名。']
    )
    password = forms.CharField(
        label='密码',
        min_length=3,
        max_length=20,
        error_messages={
            'required': '密码不能为空',
            'min_length': '密码不能少于3位',
            'max_length': '密码不能大于20位'
        },
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': '密码'}),
        help_text=['你的密码必须包含至少 3 个字符；', '你的密码必须包含不能大于 20 个字符。']
    )
    confirm_password = forms.CharField(
        label='确认密码',
        min_length=3,
        max_length=20,
        error_messages={
            'required': '请输入与上面相同的密码',
        },
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': '密码确认'}),
        help_text=['为了校验，请输入与上面相同的密码。']
    )
    link = forms.EmailField(
        label='邮箱',
        error_messages={
            'required': '邮箱不能为空',
            'invalid': '无效的邮箱格式'
        },
        widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': '邮箱'}),
        help_text=['邮箱不能为空。']
    )

    # avatar = forms.ImageField(
    #     label='头像'
    # )

    def clean_username(self):
        """校验用户名是否存在"""
        username = self.cleaned_data.get("username")
        is_exist = Author.objects.filter(username=username)
        if is_exist:
            self.add_error('username', '用户名已存在')
        return username

    def clean(self):
        """全局校验"""
        password = self.cleaned_data.get("password")
        confirm_pwd = self.cleaned_data.get("confirm_password")
        if password != confirm_pwd:
            self.add_error('confirm_password', '两次输入的密码不一致')
        return self.cleaned_data


class LoginForm(forms.Form):
    """用户登陆表单"""
    username = forms.CharField(
        label='用户名',
        min_length=3,
        max_length=8,
        error_messages={
            'required': '用户名不能为空',
            'min_length': '用户名不能少于3位',
            'max_length': '用户名不能大于8位'
        },
        widget=forms.TextInput(attrs={
            'class': 'form-control',
            'placeholder': '用户名'
        }),
    )
    password = forms.CharField(
        label='密码',
        min_length=3,
        max_length=20,
        error_messages={
            'required': '密码不能为空',
        },
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': '密码'}),
    )

    def clean_username(self):
        """校验用户名是否存在"""
        username = self.cleaned_data.get("username")
        is_exist = Author.objects.filter(username=username)
        if not is_exist:
            self.add_error('username', '用户名不存在，请前往注册')
        return username

users/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.decorators import login_required

import random
import string
import logging

from users.forms import RegForm, LoginForm
from users.models import Author
from blogs.models import UserSite

from PIL import Image, ImageDraw, ImageFont

REDIRECT_FIELD_NAME = 'next'


# Create your views here.
def register(request):
    """用户注册"""
    if request.method == 'POST':
        register_form = RegForm(request.POST)
        if register_form.is_valid():
            clean_data = register_form.cleaned_data
            username = clean_data['username']
            avatar_obj = request.FILES.get('avatar', None)
            if avatar_obj:
                clean_data['avatar'] = avatar_obj
            clean_data.pop('confirm_password')
            user = Author.objects.create_user(**clean_data)
            # 注册用户时，自动创建站点  每个用户自动关联一个站点
            UserSite.objects.create(site_title='%s的个人博客' % username, site_name='',
                                    user=user)
            return HttpResponseRedirect(reverse('users:login'))
    else:
        register_form = RegForm()
    return render(request, 'users/register.html', context={'register_form': register_form})


def log_in(request):
    """用户登陆"""
    redirect_to = request.POST.get(
        REDIRECT_FIELD_NAME,
        request.GET.get(REDIRECT_FIELD_NAME, '')
    )
    # POST请求
    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            row_code = request.session['code'].lower()
            input_code = request.POST['valid_code'].lower()
            # 验证码校验(忽略大小写)
            if input_code == row_code:
                clean_data = login_form.cleaned_data
                authenticate_user = authenticate(
                    request,
                    username=clean_data['username'],
                    password=clean_data['password']
                )
                if authenticate_user is not None and authenticate_user.is_active:
                    author = Author.objects.get(username=clean_data['username'])
                    login(request, author)
                    return HttpResponseRedirect(redirect_to)
                # 用户名或密码错误
                elif not authenticate_user:
                    login_form.add_error('password', '用户名或密码错误')
                # 用户未激活
                elif not authenticate_user.is_active:
                    login_form.add_error('username', '用户名被禁用')
            else:
                login_form.valid_error = '验证码错误，请重新输入!'
    # get请求
    else:
        login_form = LoginForm()

    if not redirect_to:
        redirect_to = reverse('blogs:home')
    return render(request, 'users/login.html', context={'login_form': login_form, 'next': redirect_to})


@login_required
def log_out(request):
    """用户登出"""
    logout(request)
    return HttpResponseRedirect(reverse('blogs:home'))


def get_code(request, refresh):
    """获取验证码图片"""
    # 图片对象->画布
    img_obj = Image.new('RGB', (550, 35), get_random())
    # 绘制图片的对象
    img_draw = ImageDraw.Draw(img_obj)
    code = ''
    # 随机绘制4个字符（大、小写字母，数字）
    for i in range(1, 5):
        random_int = random.choice(string.digits)
        random_upper = random.choice(string.ascii_uppercase)
        random_lower = random.choice(string.ascii_lowercase)
        per_code = random.choice([random_int, random_lower, random_upper])
        img_font = ImageFont.truetype('static/font/荆南麦圆体.ttf', 30)
        img_draw.text((i * 100, 0), per_code, font=img_font, spacing=4, align='center')
        code += per_code
    from io import BytesIO
    # 写入内存对象
    io_bytes = BytesIO()
    img_obj.save(io_bytes, 'png')

    # 存入session会话中便于校验
    request.session['code'] = code
    print(request.session['code'])
    return HttpResponse(io_bytes.getvalue())


def get_random():
    """返回随机背景颜色"""
    return random.randint(0, 255), random.randint(0, 255), random.randint(0, 255)


@login_required
def set_pwd(request):
    """修改密码"""
    back_dic = {'code': 0, 'msg': ''}
    if request.is_ajax():
        if request.method == 'POST':
            old_password = request.POST['old_password']
            is_right = request.user.check_password(old_password)
            new_password = request.POST['new_password']
            confirm_password = request.POST['confirm_password']
            if not new_password:
                back_dic['code'] = 1001
                back_dic['msg'] = '新密码不能为空'
            else:
                if new_password == confirm_password:
                    if is_right:
                        back_dic['code'] = 1000
                        request.user.set_password(new_password)
                        request.user.save()
                        back_dic['msg'] = '修改成功，请重新登录'
                    else:
                        back_dic['code'] = 1003
                        back_dic['msg'] = '原密码错误'
                else:
                    back_dic['code'] = 1002
                    back_dic['msg'] = '确认密码与新密码不一致'

    return JsonResponse(back_dic)

templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
          integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" rel="stylesheet">
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/twitter-bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
    <div class="page-header">
        <h1 class="text-center">用户登录</h1>
    </div>

    <div>
<!--        注册表单-->
        <form action="{% url 'users:login' %}" method="post" class="form" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in login_form %}
            <div class="form-group">
                {{ field.label_tag }}
                {{ field }}
                {% if field.errors.0 %}
                <span style="color: red; text-size:12px" class="pull-right">{{ field.errors.0}}</span>
                {% else %}
                {% if field.help_text %}
<!--                帮助文档-->
                <div class="help-block">
                    <ul>
                        {% for help in field.help_text %}
                        <li> {{ help }}</li>
                        {% endfor %}
                    </ul>
                </div>
                {% endif%}
                {% endif %}
            </div>
            {% endfor %}
<!--            验证码字段-->
            <div class="form-group">
                <label for="validate">验证码</label>
                <div class="row">
                    <div class="col-md-6">
                        <input type="text" class="form-control" name="valid_code" id="validate">
                    </div>
                    <div class="col-md-6">
                        {% load static %}
                        <img src="{% url 'users:get_code' 0 %}" class="form-control" style="padding:0px 0px" id="valid_code">
                    </div>

                </div>
                {% if login_form.valid_error %}
                <span style="color: red" class="pull-right">{{ login_form.valid_error }}</span>
                {% endif %}

            </div>
            <input type="submit" class="btn btn-success" id="commit" value="登录">
<!--            登录成功后的跳转url-->
            <input type="hidden" name="next" value="{{ next|escape}}">
        </form>
    </div>
</div>
<script>
// 点击验证码图片切换，验证码
$(function() {
    var i = 0
    $('#valid_code').click(function(){
        i += 1
        var link = $(this).attr('src')
        link = '/users/get_code/' + i.toString()
        $(this).attr('src', link)
    })
})
</script>
</body>
</html>

templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
    <!--    <link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/5.1.1/css/bootstrap.min.css">-->
    <!--    <script src="https://cdn.staticfile.org/jquery/1.10.2/jquery.min.js"></script>-->
    <link crossorigin="anonymous" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
          integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" rel="stylesheet">
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/twitter-bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
    <div class="page-header">
        <h1 class="text-center">用户注册</h1>
    </div>

    <div>
        <form action="{% url 'users:register' %}" method="post" class="form" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in register_form %}
            <div class="form-group">
                <label class="control-label">{{ field.label }}</label>
                {{ field }}
                {%  if field.errors.0 %}
                <span style="color: red; text-size:12px" class="pull-right">{{ field.errors.0}}</span>
                {% else %}
<!--                帮助文档-->
                    {% if field.help_text %}
                    <div class="help-block">
                        <ul>
                            {% for help in field.help_text %}
                            <li> {{ help }} </li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% endif%}
                {% endif %}
            </div>
            {% endfor %}
<!--            用户头像上传-->
            <div class="form-group">
                <label class="control-label" for="myfile">头像
                {% load static%}
                <img src="{% static 'users/default.jpg' %}" id="myimg" width="80px" style="margin-left: 20px">
                </label>
                <input type="file" id="myfile" name="avatar" style="display: None">
            </div>

            <input type="submit" class="btn btn-primary" id="commit" value="注册">
        </form>
    </div>
</div>

</div>
<script>
// 上传头像后，本地显示缩略图
$(function(){
    $('#myfile').change(function(){
        // 路径->fileObj.URL->FileReader()->file
        // 实例化文件阅读器
        let fileReadeObj = new FileReader();
        // 获取当前文件
        let fileObj = $(this)[0].files[0];
        fileReadeObj.readAsDataURL(fileObj);
        // 回调函数中改变img的src属性
        fileReadeObj.onload = function (){
            $('#myimg').attr('src', fileReadeObj.result)
        };
    });
});
</script>
</body>
</html>